### ISSUE TITLE
TypeError: Bad argument

### ISSUE THREAD

**Issue by ThisOneDude** [brenden/node-webshot#168]
Hello.

My code:
var renderStream = webshot('google.com');
//It dies at this command ^
var file = fs.createWriteStream('google.png', {encoding: 'binary'});

renderStream.on('data', function(data) {
file.write(data.toString('binary'), 'binary');
});

Error:
internal/child_process.js:289
  var err = this._handle.spawn(options);
                         ^(points at spawn)

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:380:9)
    at Function.spawn (/var/ftp/share/mybot/node_modules/cross-spawn/index.js:87:19)
    at spawnPhantom (/var/ftp/share/mybot/node_modules/webshot/lib/webshot.js:201:32)
    at spawn (/var/ftp/share/mybot/node_modules/webshot/lib/webshot.js:105:14)
    at module.exports (/var/ftp/share/mybot/node_modules/webshot/lib/webshot.js:121:12)
    at Client.bot.on.msg (/var/ftp/share/mybot/botFrank.js:38:22)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)

I already reinstalled phantomjs, due to seeing this being related to that in another issue.
Any other suggestions?

Thanks in advance, and best regards.

**Comment by nathanfrancy** [comment]
I'm seeing this too, did you figure out what this was?

**Comment by darrylyoung** [comment]
It might be worth checking if PhantomJS installed correctly. I just had the same issue and spent a couple of hours trying to debug it. I came across issue [#42](https://github.com/brenden/node-webshot/issues/42) and tried installing PhantomJS globally on my computer with brew. Once that was done I no longer saw the issue.

Now, that's not really a solution but it made me think to check `package.json` here and I saw that a version of PhantomJS is set as under `optionalDependencies` (see [here](https://github.com/brenden/node-webshot/blob/master/package.json#L29-L31)). My guess is that it didn't install locally for me but it might be different for you.

Anyway, I hope you also manage to resolve your issue. 👍

**Comment by impactcolor** [comment]
I'm having the same issue, were you able to resolve it? If so how?  @nathanfrancy  @ThisOneDude
