### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by surbhimundra** [brenden/node-webshot#170]
I am not able to run the simple test also. Prompts me for this error:

 cb(code
        ^

TypeError: cb is not a function
    at ChildProcess.<anonymous> (/Users/ssjmsjk/Desktop/Repo/automation-dashboards/node_modules/webshot/lib/webshot.js:248:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by surbhimundra** [comment]
Closing. I was missing calback
