### ISSUE TITLE
PhantomJS exited with return value 1

### ISSUE THREAD

**Issue by Wector** [brenden/node-webshot#225]
I keep getting this error:

Error: PhantomJS exited with return value 1
    at ChildProcess.<anonymous> (C:\xampp\htdocs\cURL\Wish_Module\webshot\node_modules\webshot\lib\webshot.js:249:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

My code is:
`var webshot = require("webshot")

var options = {
	streamType: "png",
	windowsSize: {
		width: 1024,
		height: 786
	},
	shotSize: {
		width: 660,
		height: 800
	},
	quality: 90,
	shotOffset: {
		left: 180,
		top: 20
	}
};

webshot("http://google.com","img/full.png",options, (err) => {
	if(err){
		return console.log(err);
	}
	console.log("Image succesfully created");
})`

Whats going on?

**Comment by blurfx** [comment]
you can re-install or downgrade `phantomjs-prebuilt` module. it helped me.

**Comment by jdvalentini** [comment]
Any luck with this @Wector ? I have the exact same problem, however to me it happens only when compiled, not happening when I run the code with node. Thanks!

**Comment by frizurd** [comment]
struggling with the same issue, did you solve the problem @jdvalentini ?

**Comment by jdvalentini** [comment]
> struggling with the same issue, did you solve the problem @jdvalentini ?

Hey @frizurd, Actually I have not, I posted a [question in StackOverflow](https://stackoverflow.com/questions/52561076/node-js-compiled-pkg-wont-run-but-does-from-node) and the single reply helped, but then I kept finding other problems until I gave up. I was trying to migrate a code from an already working program on electron, finally I just stayed with this one.
