### ISSUE TITLE
`primordials` is not defined - Node v12

### ISSUE THREAD

**Issue by JMTK** [brenden/node-webshot#240]
```js
ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (node_modules/natives/index.js:143:24)
    at Object.req [as require] (node_modules/natives/index.js:55:10)
    at Object.<anonymous> (node_modules/webshot/node_modules/graceful-fs/fs.js:1:37)
```

I'm using the webshot modules but it's the inner workings of the `graceful-fs`. I tried upgrading it to `4.x` and it works fine so I think that's the ticket

**Comment by zoness32** [comment]
I can confirm this fixes the issue.

Created a PR to fix this: https://github.com/brenden/node-webshot/pull/243

**Comment by architjn** [comment]
Seems like the project is not being updated since 2016.
So I have created a project clone solving this issue.

GitHub - https://github.com/architjn/node-webshot 
npmjs - https://www.npmjs.com/package/webshot-node

**Comment by juanpmd** [comment]
> Seems like the project is not being updated since 2016.
> So I have created a project clone solving this issue.
> 
> GitHub - https://github.com/architjn/node-webshot
> npmjs - https://www.npmjs.com/package/webshot-node

Amazing, it works perfectly. Thank you

**Comment by itzBawantha** [comment]
> Seems like the project is not being updated since 2016.
> So I have created a project clone solving this issue.
> 
> GitHub - https://github.com/architjn/node-webshot
> npmjs - https://www.npmjs.com/package/webshot-node

Thank you amazing work
